sonar.projectKey=veronica-tes06_TicketMaster
sonar.organization=veronica-tes06
sonar.host.url=https://sonarcloud.io
sonar.sources=app
sonar.tests=tests
sonar.exclusions=tests/**, vendor/**, build/**, app/views/**
sonar.php.coverage.reportPaths=build/coverage/clover.xml
